### ISSUE TITLE
How to use open GA

### ISSUE THREAD

**Issue by shaque6828** [Arash-codedev/openGA#1]
I am facing problem during starting. Is there any particular software for openGA? Otherwise, how I will run the software? Where from I can import some example problems? Can you please share a complete video from starting the openGA to the end of an example problem?

**Comment by Arash-codedev** [comment]
Hi shaque6828,
Apology for a late response. 
openGA is written in C++. If you are on windows, you can compile it via `VS`. On Linux, you can use `gcc` or `clang` compiler.
In the `examples` folder, there are a few examples.
In addition, in the `assist` folder, the web page helps you creating the initial code.
Would you please advise where you have stuck with using this library?
