### ISSUE TITLE
Where is the  evaluation function

### ISSUE THREAD

**Issue by mshmoon** [Arash-codedev/openGA#11]
Firstly,thank for you  excellent work.But I have a question about where is the  evaluation function.

**Comment by Arash-codedev** [comment]
Hi mshmoon.
Sorry for the late response.
Thanks for using openGA. The evaluation function is [here](https://github.com/Arash-codedev/openGA/blob/master/examples/so-1/example_so1.cpp#L40).
It is set at [here](https://github.com/Arash-codedev/openGA/blob/master/examples/so-1/example_so1.cpp#L142).
