### ISSUE TITLE
Extension

### ISSUE THREAD

**Issue by mickey4u** [Arash-codedev/openGA#2]
Just want to know how do you have documentation for extending your library. For instance if I want to create a specialised Genome class based on that of openGA library.

**Comment by Arash-codedev** [comment]
Dear Mickey,
Thank you very much for contacting me. Just letting you know that sending email will be responded faster as I check it more often than github. My email address is arash.m [at] research.deakin.edu.au

I am not sure about the details of your requirements. Would you please explain in what aspects is your chromosome structure special compared with typical ones?

Best regards,
Arash
