### ISSUE TITLE
Documentation for examples

### ISSUE THREAD

**Issue by zidane611** [Arash-codedev/openGA#9]
Hi Dr. Mohammadi,

Thanks for sharing your excellent work. That will be very helpful if you add some explanations for those examples, such as objective functions and constraints etc.  The user will be easier to know what the code is doing instead of stepping into the code.

Thanks a lot,
ZZ

**Comment by Arash-codedev** [comment]
Dear Zidane,
Thank you very much for your comment. This is actually useful for the other users too. I have placed this to my to-do list. It will take a while to apply. However, if you have any urgent question about any particular example, please feel free to ask here.
